
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import 'react-image-crop/dist/ReactCrop.css';
import { UserProvider } from "./context/UserContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Next.js 14 Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navbar />
          {children}
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
